### ISSUE TITLE
Compile error on Mac 

### ISSUE THREAD

**Issue by marvic41** [Cropdev/CropDev#14]
Hello,

Trying to compile on Mac 10.10.x. Got errors.
`/Users/oumamartabi/CropDev/src/db.h:18:10: fatal error: 'db_cxx.h' file not
found
#include <db_cxx.h>
^
1 error generated.
make: *** [obj/init.o] Error 1
Oumamas-MacBook-Pro:src oumamartabi$`

How to solve this.

thanks

**Comment by prateektiwari7** [comment]
You will get answer from here 

https://bitcointalk.org/index.php?topic=129861.0;all
